### ISSUE TITLE
No Setup.py

### ISSUE THREAD

**Issue by 336459** [GokulNC/Indic-PersoArabic-Script-Converter#1]
Hi I've been trying to install this package, but with no setup.py I've been finding it a little tricky to get it working?

**Comment by GokulNC** [comment]
Hi! Can you please let me know exactly what are you trying to achieve?

Because the development is still in progress, and not all functionalities are available yet.

**Comment by 336459** [comment]
Ah right. At the moment, I was only trying to access the Sangam API, as I've been looking for a way to post a request to their servers with Python.

**Comment by GokulNC** [comment]
Ohh, that should just work fine.
Just clone the repo.
`cd` into it.
Open your python terminal.

Use the sangam_api.convert() function as mentioned in the README

**Comment by 336459** [comment]
Thank you!
